const DynamicTipSeed = [
  {
    text: 'Oi, meu nome é Scratch Buddy, se precisar de ajuda, clique em mim!',
    markdownText:
      'Oi, meu nome é Scratch Buddy, se precisar de ajuda, clique em mim!',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'intro',
    blockId: 0,
  },
  {
    text: 'Ooops, bloco fora da área permitida',
    markdownText: 'Ooops, bloco fora da área permitida',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'outside',
    blockId: 0,
  },
  {
    text: 'Tente colocar um bloco de eventos para iniciar ...',
    markdownText: 'Tente colocar um bloco de eventos para iniciar ...',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'top_block',
    blockId: 0,
  },

  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 1,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 2,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 3,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 4,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 5,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 6,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 7,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 8,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 9,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 10,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 11,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 12,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 13,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 14,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 15,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 16,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 17,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 18,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 19,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 20,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 21,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 22,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 23,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 24,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 25,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 26,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 27,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 28,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 29,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 30,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 31,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 32,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 33,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 34,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 35,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 36,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 37,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 38,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 39,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 40,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 41,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 42,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 43,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 44,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 45,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 46,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 47,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 48,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 49,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 50,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 51,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 52,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 53,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 54,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 55,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 56,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 57,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 58,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 59,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 60,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 61,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 62,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 63,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 64,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 65,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 66,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 67,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 68,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 69,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 70,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 71,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 72,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 73,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 74,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 75,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 76,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 77,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 78,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 79,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 80,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 81,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 82,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 83,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 84,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 85,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 86,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 87,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 88,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 89,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 90,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 91,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 92,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 93,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 94,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 95,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 96,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 97,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 98,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 99,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 100,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 101,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 102,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 103,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 104,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 105,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 106,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 107,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 108,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 109,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 110,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 111,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 112,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 113,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 114,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 115,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 116,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 117,
  },
  {
    text: 'Teste um, dois, três',
    markdownText: 'Teste um, dois, três',
    secondsUntilDisplay: 5,
    secondsDisplaying: 5,
    show: 1,
    type: 'tip',
    blockId: 118,
  },
];

export default DynamicTipSeed;
